plugins {
    id 'multiloader-loader'
	id 'net.fabricmc.fabric-loom-remap'
}

final def includeModMenu = project.hasProperty("launch_with_modmenu") && project.launch_with_modmenu.toBoolean()
final def includeClothConfig = project.hasProperty("launch_with_cloth_config") && project.launch_with_cloth_config.toBoolean()

repositories {
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
	mappings loom.layered {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
	}
	modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

	if (includeModMenu) {
		modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
	} else {
		modCompileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
	}

	if (includeClothConfig) {
		modImplementation("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}")
	} else {
		modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}")
	}
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'modCompileClasspath'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
