# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_version=1.1-1.21.11
# stable, beta, alpha
version_type=beta
group=me.Azz_9.unbounded_bundle
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Unbounded Bundle
mod_author=Azz_9
mod_id=unbounded_bundle
license=MIT
description=Removes the 12-item display limit on bundles and replaces the fixed tooltip with a scrollable, dynamically-sized grid.
minecraft_compatibility=1.21.11
minecraft_version_range=[1.21.11, 1.22)
minecraft_version_start=1.21.11
minecraft_version_end=1.21.11
issues=https://github.com/Azz-9/Unbounded-bundle/issues
sources=https://github.com/Azz-9/Unbounded-bundle
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# Parchment is layered on top of the official Mojang mappings.
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# https://maven.fabricmc.net/fabric-loom/fabric-loom.gradle.plugin/maven-metadata.xml
fabric_loom=1.17.20
# https://projects.neoforged.net/neoforged/moddevgradle
neoforged_mod_dev_gradle=2.0.146
# https://modmuss50.github.io/mod-publish-plugin/
publish_plugin_version=2.2.0
# https://github.com/FabricMC/fabric-loader/blob/master/gradle.properties#L12
mixin_version=0.17.4+mixin.0.8.7
# https://github.com/FabricMC/fabric-loader/blob/master/gradle.properties#L13
mixin_extras_version=0.5.5

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.11.44
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
# https://modrinth.com/mod/modmenu/versions
modmenu_version=17.0.0
launch_with_modmenu=true
# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=21.11.153
launch_with_cloth_config=true