# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_version=1.1-26.1
# stable, beta, alpha
version_type=beta
group=me.Azz_9.unbounded_bundle
java_version=25

# Common
minecraft_version=26.1
mod_name=Unbounded Bundle
mod_author=Azz_9
mod_id=unbounded_bundle
license=MIT
description=Removes the 12-item display limit on bundles and replaces the fixed tooltip with a scrollable, dynamically-sized grid.
minecraft_compatibility=~26.1
minecraft_version_range=[26.1, 26.2)
minecraft_version_start=26.1
minecraft_version_end=26.1.2
issues=https://github.com/Azz-9/Unbounded-bundle/issues
sources=https://github.com/Azz-9/Unbounded-bundle
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.76
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0
launch_with_modmenu=true

# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=26.1.154
launch_with_cloth_config=true